### ISSUE TITLE
Action Item for this week

### ISSUE THREAD

**Issue by jennykim1016** [jennykim1016/SLRealizer#36]
Including the lists that I still have in #33 , close #33 

===========================================================

- [x] ADD THE ERROR BARS. `flux_err` is not doing the right thing. `flux_err` or all the errors should be the same for lensed system given a same visit
_flux_err is given by Fb / 5. observation history has m_5\sigma, so use fogson's law to calculate magnitude. Zeropoint: 22.5_ #37 
- [x] make a shell script to compute the `source table`. Here, source table loop through `N` lenses for `m` visits. Right now I am running the code in jupyter, but maybe a script that can run by the terminal command will be better. Somehow link it with dropbox or other cloud system -- mac will complain that is does not have any space. Do not add it to Git for now.
- [x] after making the source table, make an object table. For each lens, average the filter.
- [ ] UNIT TEST BEFORE MOVING ONTO THE CORNERPLOT #37 
- [x] #37 Functionality done, but style has to be changed.
- [x] source extraction. We can do that in #34.
Possible features would be : 

- ellipticity (qxx-qyy/(qxx+qyy)) = e1, 2qxy / (qxx + qyy) = e2, and e = (e1^2+e2^2)^2
- Size, which is given by the determinant of the covariance matrix
- Object color
- positions (maybe g-z, if the filters are too close we might not get useful info)

=====================================================================

EXT)
- [x] For now ignore RA and DEC. Think of a way to compute errors for size
- _make SLRealizer work with other catalogs too - not just OM10. This might be a major change - the code might change a lot - so need to make another branch. Do it later though, first finish generating the mock source and object catalogs_ for now we are not doing this

**Comment by jennykim1016** [comment]
More action items from the Tuesday Meeting

- [x] Comment Jupyter notebook so that it looks more beautiful!
- [x] check the unit for x and y. LSST's resolution can go around ~15milli arcsec.
- [x] fix the magnification calculation
- [x] add more features to the notebook. Especially the difference between mags for filters vs something else (size, ellipticity)

**Comment by jennykim1016** [comment]
The way for computing errors of sizes:

I couldn't find relevant papers that deal with computing errors of the computed sizes, but this is the paper that I ran into:
https://arxiv.org/pdf/0806.4089.pdf
<img width="343" alt="screen shot 2017-08-09 at 1 26 15 pm" src="https://user-images.githubusercontent.com/18297066/29142312-72560fde-7d06-11e7-85d0-5d03bb601d9d.png">

**Comment by jennykim1016** [comment]
AstroML
http://www.astroml.org/book_figures/chapter6/index.html#book-fig-chapter6

**Comment by drphilmarshall** [comment]
Did you look into the geometric interpretation of the determinant of the
covariance / second moment matrix? This seems like something that could be
proportional to size squared. Remember, we are after a _feature_ here - a
summary of the measured data that captures some important physical
information. You can define "size" as you like, as long as it has a
sensible geometric interpretation. Another way to put it: what's wrong with
just (qxx + qyy)?

**Comment by jennykim1016** [comment]
Sorry, I again made a confusion in the previous post -- I will edit it. I already computed size by calculating the determinant of the covariance matrix, and I was researching about the ways to compute errors for the size. 

And just now I was looking at this slide from a radio observatory's tutorial session about image analysis, and they assume the same error for both first moments and the size:

<img width="933" alt="screen shot 2017-08-09 at 3 36 45 pm" src="https://user-images.githubusercontent.com/18297066/29146926-b809a39e-7d18-11e7-8053-a486236a8bf6.png">

\url{http://www.hartrao.ac.za/synthesis_school/Miod_ER+IA.pdf}[Original_pdf]

So maybe the error in the size could be approximated as ~$first_moment_err$...?

**Comment by jennykim1016** [comment]
- [x] #44 - the comments for the notebook should also change accordingly
- [x] put units in the cornerplot
_rather than using comments, I just included unit in each axis_
this fixed #44! Closes #44

**Comment by jennykim1016** [comment]
DONE
